version: "3.8"
networks:
  local_network:
    attachable: true
services:
  hibernate-reactive-hot-swap-db:
    image: "postgres:12.5"
    container_name: hibernate-reactive-hot-swap-db
    command: postgres -c max_prepared_transactions=64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: hibernate-reactive-hot-swap
    networks:
      - local_network